name: Scan, Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '**.ts'
      - '**.yml'
      - Dockerfile
    exclude:
      - '**.md'

env:
  IMAGE_NAME: devsecops-sample

jobs:
  ## Scan for environment variables
  gitleaks:
      name: gitleaks
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - uses: gitleaks/gitleaks-action@v2
          id: scan
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ## Docker build and push to registry
  build_and_push:
    needs: gitleaks
    name: Build and push to GitHub Packages
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./Dockerfile --tag {{ env.IMAGE_NAME }}:latest

    - name: Publish Docker image to GitHub Packages
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        docker tag {{ env.IMAGE_NAME }}:latest docker.pkg.github.com/${{ github.repository }}/{{ env.IMAGE_NAME }}:latest
        docker push docker.pkg.github.com/${{ github.repository }}/{{ env.IMAGE_NAME }}:latest

  ## Scan the docker image that we previously published
  trivy:
    permissions:
      contents: read 
      security-events: write 
      actions: read
    
    needs: build_and_push
    name: Trivy vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'ghcr.io/{{ github.actor }}/{{ github.event.repository.name }}/{{ env.IMAGE_NAME }}:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
